import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { bridge } from "./bridge";
import { expiryLabel, filterSessions, formatTimestamp, type AudioDevice, type CleanupLevel, type BriefItem, type DictationDetail, type DictationEvent, type MeetingDetail, type MeetingEvent, type MeetingPromptEvent, type Preferences, type ProcessingMode, type SessionSummary, type SetupProgressEvent, type SetupStatus, type VocabularyEntry } from "./domain";
import { defaultPreferences, meeting as sampleMeeting, sessions as sampleSessions, vocabulary as sampleVocabulary } from "./fixtures";
import { Icon } from "./icons";

type View = "library" | "meeting" | "vocabulary" | "settings";
type Notice = { kind: "success" | "error" | "attention"; text: string } | null;
const statusText: Record<SessionSummary["status"], string> = { inserted: "Inserted", clipboard: "On clipboard", raw: "Raw", capturing: "Capturing", processing: "Processing", completed: "Transcribed", failed: "Failed", cancelled: "Cancelled", "brief-ready": "Brief ready", "brief-pending": "Brief pending" };
const sampleSetup: SetupStatus = {
  checks: [{ id: "microphone", label: "Microphone", detail: "Browser preview cannot test Windows audio", state: "unavailable" }, { id: "insertion", label: "Text insertion", detail: "Browser preview cannot test accessibility insertion", state: "unavailable" }, { id: "offline", label: "Offline speech", detail: "Large V3 Turbo is shown as a fixture", state: "unavailable" }],
  providers: [{ id: "groq", label: "Groq", configured: false, state: "missing", detail: "Not connected" }],
  update: { state: "current", detail: "Sample status · Browser preview" },
};

function errorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  if (typeof error === "string") return error;
  if (error && typeof error === "object") {
    const value = error as { message?: unknown; error?: unknown };
    if (typeof value.message === "string") return value.message;
    if (typeof value.error === "string") return value.error;
  }
  return "The native operation failed.";
}
function ModeDot({ mode }: { mode: ProcessingMode }) { return <span className={`mode-dot mode-${mode}`} aria-label={mode.replace("-", " ")} />; }
function Button({ children, className = "", icon, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { icon?: Parameters<typeof Icon>[0]["name"] }) { return <button className={`button ${className}`} {...props}>{icon && <Icon name={icon} size={15} />}{children}</button>; }
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (checked: boolean) => void; label: string }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} className={`toggle ${checked ? "on" : ""}`} onClick={() => onChange(!checked)}><span /></button>; }
function Empty({ title, body }: { title: string; body: string }) { return <div className="empty"><Icon name="search"/><strong>{title}</strong><span>{body}</span></div>; }
function NoticeBar({ notice, onDismiss }: { notice: NonNullable<Notice>; onDismiss: () => void }) { return <div className={`shell-notice ${notice.kind}`} role={notice.kind === "error" ? "alert" : "status"}><span>{notice.text}</span><button onClick={onDismiss} aria-label="Dismiss message"><Icon name="x" size={13}/></button></div>; }

type OverlayVisualState = "recording" | "transcribing" | "correcting" | "inserting" | "success" | "fallback" | "failed" | "cancelled";
const SIGNAL_BARS = 12;
const SIGNAL_FLOOR = 0.08;

function displayLevel(rms: number, peak: number): number {
  const toVisual = (value: number) => Math.min(1, Math.max(0, (20 * Math.log10(Math.max(value, 0.000001)) + 55) / 47));
  return Math.max(toVisual(rms), toVisual(peak) * 0.72);
}

function dictationLabel(event: DictationEvent | null): string {
  if (!event) return "";
  const labels: Record<DictationEvent["state"], string> = { idle: "", recording: "Listening", transcribing: "Transcribing", correcting: "Correcting", inserting: "Inserting", inserted: `Inserted${event.targetApp ? ` into ${event.targetApp}` : ""}`, clipboard: "Kept on clipboard", raw: "Inserted raw transcript", failed: "Dictation failed", cancelled: "Cancelled" };
  return labels[event.state];
}

function DictationAnnouncer({ event }: { event: DictationEvent | null }) {
  const label = dictationLabel(event);
  const failed = event?.state === "failed";
  return <><span className="visually-hidden" role="status" aria-live="polite" aria-atomic="true">{failed ? "" : label}</span><span className="visually-hidden" role="alert" aria-live="assertive" aria-atomic="true">{failed ? label : ""}</span></>;
}

function SpeechSignal({ event, visualState }: { event: DictationEvent; visualState: OverlayVisualState }) {
  const bars = useRef<Array<HTMLSpanElement | null>>([]);
  useEffect(() => {
    if (event.state !== "recording" || !event.sessionId) return;
    const reducedMotion = window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false;
    if (reducedMotion) return;
    let disposed = false;
    let off: () => void = () => undefined;
    const history = Array<number>(SIGNAL_BARS).fill(SIGNAL_FLOOR);
    void bridge.listen("murmur://dictation-audio-level", (level) => {
      if (disposed || level.sessionId !== event.sessionId) return;
      history.push(Math.max(SIGNAL_FLOOR, displayLevel(level.rms, level.peak)));
      history.shift();
      bars.current.forEach((bar, index) => {
        if (bar) bar.style.transform = `scaleY(${history[index] ?? SIGNAL_FLOOR})`;
      });
    }).then((unlisten) => { if (disposed) unlisten(); else off = unlisten; });
    return () => { disposed = true; off(); };
  }, [event.sessionId, event.state]);

  if (event.state === "recording") return <span className="speech-signal speech-live" data-speech-signal aria-hidden="true">{Array.from({ length: SIGNAL_BARS }, (_, index) => <span key={index} ref={(bar) => { bars.current[index] = bar; }} style={{ transform: `scaleY(${SIGNAL_FLOOR})` }}/>)}</span>;
  const stage = event.state === "transcribing" ? 0 : event.state === "correcting" ? 1 : event.state === "inserting" ? 2 : -1;
  if (stage >= 0) return <span className={`speech-signal speech-stages ${visualState === "fallback" ? "is-fallback" : ""}`} aria-hidden="true">{[0, 1, 2].map((index) => <span key={index} className={index < stage ? "complete" : index === stage ? "current" : "pending"}><i /></span>)}</span>;
  const glyph = visualState === "success" ? <Icon name="check" size={15}/> : visualState === "fallback" ? "↳" : visualState === "failed" ? "!" : "×";
  return <span className={`speech-signal speech-terminal terminal-${visualState}`} aria-hidden="true"><span key={visualState}>{glyph}</span></span>;
}

function AppHeader({ view, onNavigate }: { view: View; onNavigate: (view: View) => void }) {
  return <header className="app-header"><button className="brand" onClick={() => onNavigate("library")} aria-label="Open library"><span className="brand-mark"><span /></span><strong>Murmur</strong></button><nav aria-label="Main navigation"><button className={view === "library" ? "active" : ""} onClick={() => onNavigate("library")}>Library</button><button className={view === "meeting" ? "active" : ""} onClick={() => onNavigate("meeting")}>Meetings</button><button className={view === "vocabulary" ? "active" : ""} onClick={() => onNavigate("vocabulary")}>Vocabulary</button><button className={view === "settings" ? "active" : ""} onClick={() => onNavigate("settings")}>Settings</button></nav><div className="window-actions" aria-hidden="true"><span>—</span><span>□</span><span>×</span></div></header>;
}

function DictationOverlay({ event, onCancel, onStop }: { event: DictationEvent | null; onCancel: () => void; onStop: () => void }) {
  if (!event || event.state === "idle") return null;
  const recording = event.state === "recording";
  const label = dictationLabel(event);
  const mode = event.mode ? event.mode.replace("hosted-fallback", "Hosted fallback") : "";
  const processingFallback = event.mode === "hosted-fallback" && ["transcribing", "correcting", "inserting"].includes(event.state);
  const visualState: OverlayVisualState = processingFallback ? "fallback" : event.state === "inserted" ? "success" : event.state === "clipboard" || event.state === "raw" ? "fallback" : event.state;
  const meta = recording ? `${formatTimestamp((event.elapsedMs ?? 0) / 1000)} · Esc cancels` : event.provider ?? mode ?? event.message ?? "";
  return <div className={`dictation-overlay overlay-${visualState}`} data-state={visualState}>
    <SpeechSignal key={`${event.state}-${event.mode ?? ""}`} event={event} visualState={visualState}/>
    <span className="overlay-copy" aria-hidden="true"><strong>{label}</strong><span>{meta}</span></span>
    {recording && <Button className="overlay-action" onClick={onStop}>Stop</Button>}{recording && <button onClick={onCancel} aria-label="Cancel dictation"><Icon name="x" size={13}/></button>}
  </div>;
}

function MeetingPrompt({ prompt, onDismiss, onDisable, onAction }: { prompt: MeetingPromptEvent; onDismiss: () => void; onDisable: () => void; onAction: () => void }) {
  return <aside className="meeting-prompt" role="dialog" aria-label="Meeting suggestion"><span className="permission-icon"><Icon name={prompt.kind === "start" ? "mic" : "users"}/></span><div><strong>{prompt.kind === "start" ? "Meeting detected" : "Meeting may have ended"}</strong><span>{prompt.title ?? prompt.appName}</span></div>{prompt.kind === "start" && <button className="prompt-link" onClick={onDisable}>Don't suggest for {prompt.appName}</button>}<Button className="primary" onClick={onAction}>{prompt.kind === "start" ? "Start recording" : "Stop recording"}</Button><button className="icon-button" onClick={onDismiss} aria-label="Dismiss suggestion"><Icon name="x" size={14}/></button></aside>;
}

function Library({ onOpenMeeting, onNavigateSettings, dictation, meetingState, setNotice }: { onOpenMeeting: (id: string) => void; onNavigateSettings: () => void; dictation: DictationEvent | null; meetingState: MeetingEvent | null; setNotice: (notice: Notice) => void }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState(""); const [items, setItems] = useState<SessionSummary[]>(bridge.isNative ? [] : sampleSessions); const [detail, setDetail] = useState<DictationDetail | null>(null); const [loading, setLoading] = useState(bridge.isNative); const [copied, setCopied] = useState(false);
  const load = useCallback(async () => { if (!bridge.isNative) return; setLoading(true); try { const loaded = await bridge.listSessions(query); setItems(loaded); } catch (error) { setNotice({ kind: "error", text: `Could not load local sessions. ${errorMessage(error)}` }); } finally { setLoading(false); } }, [query, setNotice]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), query ? 180 : 0); return () => clearTimeout(timer); }, [load, query]);
  useEffect(() => { if (!bridge.isNative) return; let off: () => void = () => undefined; void bridge.listen("murmur://sessions-changed", () => void load()).then((unlisten) => { off = unlisten; }); return () => off(); }, [load]);
  const filtered = useMemo(() => bridge.isNative ? items : filterSessions(items, query), [items, query]); const selectedItem = items.find((item) => item.id === selected);
  const act = async (action: () => Promise<unknown>, success?: string) => { try { await action(); setNotice(success ? { kind: "success", text: success } : null); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const startDictation = async () => { try { await bridge.startDictation(); setNotice(null); } catch (error) { setNotice({ kind: "error", text: `Recording did not start. ${errorMessage(error)}` }); } };
  const importAudio = () => void (async () => { try { const id = await bridge.importRecording(); if (!id) return; setNotice({ kind: "success", text: "Recording imported. Transcription has started." }); onOpenMeeting(id); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } })();
  const startMeeting = (source: "online" | "in-person") => void act(() => bridge.startMeeting(source), `${source === "online" ? "Online" : "In-person"} meeting recording started.`);
  const selectSession = async (session: SessionSummary) => { setSelected(session.id); setDetail(null); if (session.kind === "meeting") { onOpenMeeting(session.id); return; } if (!["completed", "inserted", "clipboard", "raw"].includes(session.status)) return; if (bridge.isNative) try { const loaded = await bridge.getDictationDetail(session.id); setDetail(loaded); setItems((current) => current.map((item) => item.id === session.id ? { ...item, status: loaded.uncorrected ? "raw" : loaded.insertionStatus === "clipboard" ? "clipboard" : loaded.insertionStatus === "failed" ? "failed" : "inserted", rawTranscript: loaded.rawTranscript, provider: loaded.provider } : item)); } catch (error) { setNotice({ kind: "error", text: `Could not load dictation details. ${errorMessage(error)}` }); } };
  const transform = (action: "rewrite" | "translate-english" | "translate-vietnamese") => { if (!selectedItem) return; void act(async () => { const changed = await bridge.transformDictation(selectedItem.id, action); setDetail(changed); }, action === "rewrite" ? "Rewrite ready. Copy it when you are satisfied." : "Translation ready. Copy it when you are satisfied."); };
  return <main className="library page-enter"><section className="command-surface" aria-label="Session library"><div className="search-row"><Icon name="search"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search sessions, or type a command" aria-label="Search sessions" autoFocus/><button className="voice-key" disabled={dictation?.state === "recording"} onClick={() => void startDictation()} aria-label="Start dictation"><Icon name="mic" size={16}/><span>Ctrl + Win</span></button></div>
    <div className="library-head"><span>{bridge.isNative ? "Local sessions" : "Sample data · Browser preview"}</span><div className="head-actions"><button onClick={importAudio}>Import recording</button><button onClick={() => startMeeting("online")}>Record online call</button><button onClick={() => startMeeting("in-person")}>Record in person</button></div></div>
    {meetingState?.state === "recording" && <div className="meeting-live"><span className="record-dot"/><strong>Meeting recording</strong><span>{formatTimestamp((meetingState.elapsedMs ?? 0) / 1000)} · Microphone + system audio</span><Button onClick={() => void act(() => bridge.stopMeeting(), "Meeting stopped. Transcription has started.")}>Stop meeting</Button></div>}
    <div className="session-list">{loading ? <Empty title="Loading local sessions" body="Reading Murmur's local library."/> : filtered.map((session) => <div key={session.id}><button className={`session-row ${selected === session.id ? "selected" : ""}`} onClick={() => void selectSession(session)}><ModeDot mode={session.mode}/><span className="session-copy"><strong lang={session.id === "dictation-19" ? "vi" : undefined}>{session.title}</strong><small>{session.subtitle}</small></span><span className="session-status"><time>{session.time}</time><small>{statusText[session.status]}</small></span><Icon name="chevron" size={15}/></button>{selected === session.id && session.kind === "dictation" && <div className="session-detail"><p>{detail?.result ?? session.title}</p>{(detail?.rawTranscript || session.rawTranscript) && <p className="raw"><span>Raw transcript</span>{detail?.rawTranscript ?? session.rawTranscript}</p>}<p className="technical">{detail ? `${detail.provider} · ${detail.processingMode.replace("-", " ")} · ${detail.language} · ${detail.uncorrected ? "Raw, correction unavailable" : "Corrected"} · ${detail.insertionStatus === "clipboard" ? "Kept on clipboard" : detail.insertionStatus === "failed" ? "Insertion failed" : "Inserted"} · ${detail.transcriptionMs + detail.correctionMs + detail.insertionMs} ms after capture · ${expiryLabel(detail.expiresAt)}` : `${session.provider ?? "Processing route unavailable"} · ${session.status === "clipboard" ? "Direct insertion failed. Text remains on the clipboard." : statusText[session.status]}`}</p><div className="detail-actions"><Button className="primary" icon={copied ? "check" : "copy"} onClick={() => void act(async () => { await bridge.copyText(detail?.result ?? session.title); setCopied(true); setTimeout(() => setCopied(false), 1200); })}>{copied ? "Copied" : "Copy"}</Button>{bridge.isNative && detail && <><Button onClick={() => transform("rewrite")}>Rewrite</Button><Button onClick={() => transform("translate-english")}>Translate to English</Button><Button onClick={() => transform("translate-vietnamese")}>Translate to Vietnamese</Button></>}<Button className="quiet danger" icon="trash" onClick={() => void act(async () => { await bridge.deleteSession(session.id); setItems((all) => all.filter((item) => item.id !== session.id)); }, "Session deleted.")}>Delete</Button></div></div>}</div>)}{!loading && filtered.length === 0 && <Empty title={query ? "No matching sessions" : "No sessions yet"} body={query ? "Try a different phrase or clear the search." : "Hold Ctrl + Win to dictate, record a meeting, or import audio."}/>}</div>
    <footer className="command-footer"><span>Click a session to inspect or open it.</span><span>{bridge.isNative ? "Hosted, fallback, local, and queued routes are shown per session" : "Fixture actions require the Windows app"}</span></footer></section><aside className="privacy-strip"><Icon name="spark" size={14}/><span>Focused context is discarded after correction and learning.</span><button onClick={onNavigateSettings}>Review exclusions</button></aside></main>;
}

function BriefSection({ title, items, onSeek }: { title: string; items: BriefItem[]; onSeek: (seconds: number) => void }) { return <section className="brief-section"><h3>{title}</h3>{items.length ? items.map((item) => <p key={`${title}-${item.text}`}>{item.text}{item.citationSeconds !== undefined && <button className="citation" onClick={() => onSeek(item.citationSeconds!)} aria-label={`Play citation at ${formatTimestamp(item.citationSeconds)}`}>{formatTimestamp(item.citationSeconds)}</button>}</p>) : <p className="muted-copy">None found in the transcript.</p>}</section>; }

function Meeting({ id, onBack, setNotice }: { id: string | null; onBack: () => void; setNotice: (notice: Notice) => void }) {
  const sample = !bridge.isNative; const [detail, setDetail] = useState<MeetingDetail | null>(sample ? sampleMeeting : null); const [loading, setLoading] = useState(!sample); const [mode, setMode] = useState<"edited" | "raw">("edited"); const [activeTime, setActiveTime] = useState(0); const [editing, setEditing] = useState("");
  const audioRefs = useRef<Array<HTMLAudioElement | null>>([]); const [audioUrls, setAudioUrls] = useState<string[]>([]); const [audioLoading, setAudioLoading] = useState(false);
  const load = useCallback(async (showLoading = false) => { if (!bridge.isNative || !id) return; if (showLoading) setLoading(true); try { setDetail(await bridge.getMeetingDetail(id)); } catch (error) { setNotice({ kind: "error", text: `Could not load meeting. ${errorMessage(error)}` }); } finally { if (showLoading) setLoading(false); } }, [id, setNotice]);
  useEffect(() => { void load(true); }, [load]);
  useEffect(() => { if (!bridge.isNative || !id) return; let off: () => void = () => undefined; void bridge.listen("murmur://sessions-changed", () => void load()).then((unlisten) => { off = unlisten; }); return () => off(); }, [id, load]);
  useEffect(() => { if (!bridge.isNative || !detail?.audioPaths?.length) { setAudioUrls([]); setAudioLoading(false); return; } let active = true; setAudioLoading(true); import("@tauri-apps/api/core").then(({ convertFileSrc }) => { if (active) setAudioUrls(detail.audioPaths!.filter((path) => Boolean(path) && !/[\\/]$/.test(path)).map((path) => convertFileSrc(path))); }).catch((error) => setNotice({ kind: "error", text: `Meeting audio could not be opened. ${errorMessage(error)}` })).finally(() => { if (active) setAudioLoading(false); }); return () => { active = false; }; }, [detail?.audioPaths, setNotice]);
  const act = async (action: () => Promise<unknown>, success?: string): Promise<boolean> => { try { await action(); if (success) setNotice({ kind: "success", text: success }); return true; } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); return false; } };
  if (loading) return <main className="meeting page-enter"><Empty title="Loading meeting" body="Reading transcript and Meeting Brief."/></main>;
  if (!detail) return <main className="meeting page-enter"><Empty title={id ? "Meeting unavailable" : "No meeting selected"} body={id ? "The meeting may have expired or been deleted." : "Open a meeting from the library."}/><Button onClick={onBack}>Back to library</Button></main>;
  const seek = (seconds: number) => { setActiveTime(seconds); const players = audioRefs.current.filter((player): player is HTMLAudioElement => Boolean(player)); if (players.length) { for (const player of players) player.currentTime = seconds; void Promise.allSettled(players.map((player) => player.play())).then((results) => { if (results.every((result) => result.status === "rejected")) setNotice({ kind: "error", text: "Meeting audio could not start. Check that its files still exist." }); }); } else if (audioLoading) setNotice({ kind: "attention", text: "Meeting audio is still loading." }); else setNotice({ kind: "error", text: "No playable meeting audio is available for this citation." }); };
  const saveTurn = async (turnId: string, text: string) => { if (!await act(() => bridge.saveTranscriptTurn(detail.id, turnId, text), "Transcript edit saved.")) return; setDetail((current) => current ? { ...current, turns: current.turns.map((turn) => turn.id === turnId ? { ...turn, text, edited: true } : turn) } : current); setEditing(""); };
  const rename = async (from: string) => { const to = window.prompt(`Rename speaker "${from}" to`, from)?.trim(); if (!to || to === from) return; if (!await act(() => bridge.renameSpeaker(detail.id, from, to), "Speaker label updated.")) return; setDetail((current) => current ? { ...current, turns: current.turns.map((turn) => turn.speaker === from ? { ...turn, speaker: to } : turn) } : current); };
  const exportMarkdown = async () => { try { const path = await bridge.exportMeeting(detail.id); if (path) setNotice({ kind: "success", text: "Markdown export saved." }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const cited = (item: BriefItem) => `${item.text}${item.citationSeconds === undefined ? "" : ` [${formatTimestamp(item.citationSeconds)}]`}`;
  const briefSection = (title: string, items: BriefItem[] | undefined) => items?.length ? ["", title, ...items.map((item) => `- ${cited(item)}`)] : [];
  const briefText = [detail.title, "", "Overview", detail.overview, ...briefSection("Detailed topics", detail.topics), ...briefSection("Decisions", detail.decisions), ...briefSection("Action items", detail.actions), ...briefSection("Open questions", detail.questions), ...briefSection("Notable moments", detail.notableMoments), ...briefSection("Possible follow-ups", detail.followUps)].join("\n");
  const citationsComplete = [...detail.decisions, ...detail.actions].every((item) => item.citationSeconds !== undefined);
  return <main className="meeting page-enter"><div className="meeting-titlebar"><button className="icon-button" onClick={onBack} aria-label="Back to library"><Icon name="back"/></button><div><div className="meeting-title-line"><h1>{detail.title}</h1>{sample && <span className="sample-badge">Sample data · Browser preview</span>}</div><p>{detail.date} · {detail.duration} · {detail.speakers} speakers · {detail.pinned ? "Kept indefinitely" : expiryLabel(detail.expiresAt)}</p></div><div className="meeting-actions"><Button icon="pin" className={detail.pinned ? "selected-button" : ""} onClick={() => void act(async () => { await bridge.setMeetingPinned(detail.id, !detail.pinned); setDetail({ ...detail, pinned: !detail.pinned }); })}>{detail.pinned ? "Kept" : "Keep"}</Button><Button icon="copy" onClick={() => void act(() => bridge.copyText(briefText), "Meeting Brief copied.")}>Copy brief</Button><Button onClick={() => void exportMarkdown()}>Export Markdown</Button></div></div>
    {detail.status === "pending" && <div className="pending-banner"><span className="attention-mark">!</span><div><strong>Waiting to finish online</strong><span>{detail.pendingReason ?? "Murmur will resume transcription and the Meeting Brief when a connection is available."}</span></div><Button onClick={() => void act(() => bridge.resumeEnhancement(detail.id), "Enhancement queued.")}>Try now</Button></div>}
    <div className="meeting-workspace"><article className="meeting-brief" aria-label="Meeting brief"><div className="pane-heading"><div><span className="eyebrow">Meeting brief</span><h2>What happened</h2></div>{detail.overview && <span className={`generated ${citationsComplete ? "" : "incomplete"}`}><Icon name="spark" size={13}/> {citationsComplete ? "Cited" : "Citations incomplete"}</span>}</div>{detail.overview ? <><section className="brief-section"><h3>Overview</h3><p>{detail.overview}</p></section>{detail.topics && <BriefSection title="Detailed topics" items={detail.topics} onSeek={seek}/>}<BriefSection title="Decisions" items={detail.decisions} onSeek={seek}/><BriefSection title="Action items" items={detail.actions} onSeek={seek}/><BriefSection title="Open questions" items={detail.questions} onSeek={seek}/>{detail.notableMoments && <BriefSection title="Notable moments" items={detail.notableMoments} onSeek={seek}/>} {detail.followUps && <BriefSection title="Possible follow-ups" items={detail.followUps} onSeek={seek}/>}</> : <Empty title="Brief not ready" body="The literal transcript stays available while online enhancement waits."/>}</article>
    <section className="transcript-pane" aria-label="Transcript"><div className="transcript-heading"><strong>Transcript</strong><div className="segmented"><button aria-pressed={mode === "edited"} className={mode === "edited" ? "active" : ""} onClick={() => setMode("edited")}>Edited</button><button aria-pressed={mode === "raw"} className={mode === "raw" ? "active" : ""} onClick={() => setMode("raw")}>Raw</button></div><span className="raw-lock">{mode === "raw" ? "Immutable source" : "Click text to edit"}</span></div><div className="turns">{detail.turns.length ? detail.turns.map((turn) => <article key={turn.id} className={`turn ${activeTime === turn.timestampSeconds ? "active" : ""}`}><span className="turn-meta"><button onClick={() => void rename(turn.speaker)} disabled={mode === "raw"}>{turn.speaker}</button><button onClick={() => seek(turn.timestampSeconds)}>{formatTimestamp(turn.timestampSeconds)}</button>{turn.edited && mode === "edited" && <em>edited</em>}</span>{editing === turn.id && mode === "edited" ? <span className="turn-editor"><textarea defaultValue={turn.text} aria-label={`Edit transcript at ${formatTimestamp(turn.timestampSeconds)}`}/><span><Button onClick={(event) => { const textarea = event.currentTarget.parentElement?.previousElementSibling as HTMLTextAreaElement; void saveTurn(turn.id, textarea.value); }}>Save</Button><Button onClick={() => setEditing("")}>Cancel</Button></span></span> : <button className="turn-text" onClick={() => mode === "edited" ? setEditing(turn.id) : seek(turn.timestampSeconds)}>{mode === "raw" ? turn.rawText ?? turn.text : turn.text}</button>}</article>) : <Empty title="Transcript not ready" body="Murmur keeps the audio and resumes transcription when a route is available."/>}</div>{audioUrls.map((url, index) => <audio key={url} ref={(node) => { audioRefs.current[index] = node; }} src={url} preload="metadata" onError={() => setNotice({ kind: "error", text: "A meeting audio channel could not be loaded." })} onTimeUpdate={index === 0 ? (event) => setActiveTime(event.currentTarget.currentTime) : undefined}/>)}{detail.turns.length > 0 && <div className="audio-player"><button className="play-button" aria-label="Play from selected timestamp" onClick={() => seek(activeTime)}><Icon name="play" size={16}/></button><time>{formatTimestamp(activeTime)}</time><div className="audio-track"><span style={{ width: `${Math.min(100, (activeTime / (detail.durationSeconds || 1)) * 100)}%` }}/></div><time>{detail.duration}</time><span className="source"><Icon name="users" size={14}/> {audioUrls.length > 1 ? "Mic + system" : "Meeting audio"}</span></div>}</section></div></main>;
}

function Vocabulary({ setNotice }: { setNotice: (notice: Notice) => void }) {
  const [entries, setEntries] = useState<VocabularyEntry[]>(bridge.isNative ? [] : sampleVocabulary); const [spoken, setSpoken] = useState(""); const [replacement, setReplacement] = useState(""); const [loading, setLoading] = useState(bridge.isNative);
  useEffect(() => { if (!bridge.isNative) return; bridge.listVocabulary().then(setEntries).catch((error) => setNotice({ kind: "error", text: errorMessage(error) })).finally(() => setLoading(false)); }, [setNotice]);
  const add = async (event: React.FormEvent) => { event.preventDefault(); if (!spoken.trim() || !replacement.trim()) return; try { const entry = bridge.isNative ? await bridge.addVocabulary(spoken.trim(), replacement.trim()) : { id: crypto.randomUUID(), spoken: spoken.trim(), replacement: replacement.trim(), source: "manual" as const, uses: 0 }; setEntries((all) => [...all, entry]); setSpoken(""); setReplacement(""); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const remove = async (entry: VocabularyEntry) => { try { if (bridge.isNative) await bridge.deleteVocabulary(entry.id); setEntries((all) => all.filter((item) => item.id !== entry.id)); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const persist = async (entry: VocabularyEntry) => { if (!bridge.isNative) return; try { await bridge.updateVocabulary(entry); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); try { setEntries(await bridge.listVocabulary()); } catch { setNotice({ kind: "error", text: `${errorMessage(error)} Reload Personal Vocabulary to restore the saved values.` }); } } };
  return <main className="content-page page-enter"><header className="page-heading"><div><span className="eyebrow">Correction layer</span><h1>Personal vocabulary</h1><p>Terms are applied after transcription. Murmur never sends them as speech-recognition prompts.</p></div>{!bridge.isNative && <span className="sample-badge">Sample data · Browser preview</span>}</header><form className="add-vocabulary" onSubmit={add}><label><span>When Murmur hears</span><input value={spoken} onChange={(e) => setSpoken(e.target.value)} placeholder="was api"/></label><Icon name="chevron"/><label><span>Write</span><input value={replacement} onChange={(e) => setReplacement(e.target.value)} placeholder="WASAPI"/></label><Button className="primary" icon="plus" type="submit">Add term</Button></form><section className="vocab-table" aria-label="Vocabulary entries"><div className="table-head"><span>Heard</span><span>Correction</span><span>Source</span><span>Used</span><span/></div>{loading ? <Empty title="Loading vocabulary" body="Reading saved and learned terms."/> : entries.map((entry) => <div className="vocab-row" key={entry.id}><input aria-label={`Heard phrase for ${entry.replacement}`} value={entry.spoken} onChange={(e) => setEntries((all) => all.map((item) => item.id === entry.id ? { ...item, spoken: e.target.value } : item))} onBlur={() => void persist(entry)}/><input aria-label={`Correction for ${entry.spoken}`} value={entry.replacement} onChange={(e) => setEntries((all) => all.map((item) => item.id === entry.id ? { ...item, replacement: e.target.value } : item))} onBlur={() => void persist(entry)}/><span className={`source-tag ${entry.source}`}>{entry.source}</span><span>{entry.uses} times</span><button aria-label={`Delete ${entry.replacement}`} onClick={() => void remove(entry)}><Icon name="trash" size={15}/></button></div>)}{!loading && entries.length === 0 && <Empty title="No personal vocabulary" body="Add names and terms Murmur should write exactly."/>}</section><footer className="learning-note"><Icon name="spark"/><div><strong>Learning stays quiet</strong><p>Murmur learns after you make the same attributed correction three times.</p></div><Button onClick={() => void (async () => { try { if (bridge.isNative) await bridge.resetLearnedVocabulary(); setEntries((all) => all.filter((entry) => entry.source !== "learned")); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } })()}>Reset learned terms</Button></footer></main>;
}

function SettingRow({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="setting-row"><span><strong>{title}</strong><small>{description}</small></span>{children}</div>; }
function StateTag({ state }: { state: string }) { return <span className={`state-tag state-${state}`}>{state}</span>; }

function CredentialDialog({ provider, onClose, onSave }: { provider: { id: string; label: string }; onClose: () => void; onSave: (secret: string) => Promise<void> }) {
  const [secret, setSecret] = useState(""); const [saving, setSaving] = useState(false);
  return <div className="modal-backdrop"><form className="credential-dialog" role="dialog" aria-modal="true" aria-labelledby="credential-title" onSubmit={(event) => { event.preventDefault(); if (!secret) return; setSaving(true); void onSave(secret).finally(() => { setSecret(""); setSaving(false); }); }}><span className="eyebrow">Windows Credential Manager</span><h2 id="credential-title">Connect {provider.label}</h2><p>Murmur sends this key straight to native credential storage. It is not written to settings, logs, backups, or Git.</p><label><span>API key</span><input type="password" autoComplete="off" value={secret} onChange={(event) => setSecret(event.target.value)} autoFocus/></label><div><Button type="button" onClick={onClose}>Cancel</Button><Button className="primary" type="submit" disabled={!secret || saving}>{saving ? "Checking…" : "Save and test"}</Button></div></form></div>;
}

function Settings({ setNotice, progress, clearProgress }: { setNotice: (notice: Notice) => void; progress: SetupProgressEvent | null; clearProgress: () => void }) {
  const [prefs, setPrefs] = useState(defaultPreferences); const [prefsReady, setPrefsReady] = useState(!bridge.isNative); const [setup, setSetup] = useState(sampleSetup); const [setupReady, setSetupReady] = useState(!bridge.isNative); const [devices, setDevices] = useState<AudioDevice[]>([]); const [saved, setSaved] = useState(false); const [excluded, setExcluded] = useState(false); const [credential, setCredential] = useState<{ id: string; label: string } | null>(null); const [prefsError, setPrefsError] = useState(""); const [setupError, setSetupError] = useState(""); const [devicesError, setDevicesError] = useState("");
  const loadPreferences = useCallback(async () => { setPrefsError(""); try { setPrefs(await bridge.getPreferences()); setPrefsReady(true); } catch (error) { const message = errorMessage(error); setPrefsError(message); setNotice({ kind: "error", text: `Preferences unavailable. ${message}` }); } }, [setNotice]);
  const loadSetup = useCallback(async () => { setSetupError(""); try { setSetup(await bridge.getSetupStatus()); setSetupReady(true); } catch (error) { const message = errorMessage(error); setSetupError(message); setNotice({ kind: "error", text: `Setup status unavailable. ${message}` }); } }, [setNotice]);
  const loadDevices = useCallback(async () => { setDevicesError(""); try { setDevices(await bridge.listAudioDevices()); } catch (error) { const message = errorMessage(error); setDevicesError(message); setNotice({ kind: "error", text: `Microphone list unavailable. ${message}` }); } }, [setNotice]);
  useEffect(() => { if (!bridge.isNative) return; void loadPreferences(); void loadSetup(); void loadDevices(); }, [loadDevices, loadPreferences, loadSetup]);
  const set = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setPrefs((current) => ({ ...current, [key]: value }));
  const act = async (action: () => Promise<unknown>, success?: string) => { try { await action(); if (success) setNotice({ kind: "success", text: success }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const save = () => { if (!prefsReady) return; void act(async () => { await bridge.savePreferences(prefs); setSaved(true); setTimeout(() => setSaved(false), 1200); }, "Settings saved."); };
  const validate = (id: string) => void act(async () => setSetup(await bridge.validateProvider(id)), "Provider connection checked.");
  const runCheck = (id: string) => void act(async () => setSetup(await bridge.runSetupCheck(id)), "Setup check finished.");
  const fileAction = async (action: () => Promise<string | null>, success: string) => { try { const path = await action(); if (path) setNotice({ kind: "success", text: success }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } finally { clearProgress(); } };
  const backup = () => { if (window.confirm("This plain ZIP contains transcripts, Personal Vocabulary, settings, and meeting audio. It excludes credentials. Create it now?")) void fileAction(() => bridge.createBackup(), "Backup saved."); };
  const restore = () => { if (window.confirm("Restore a Murmur backup? Existing matching records may be replaced after validation.")) void fileAction(() => bridge.restoreBackup(), "Backup verified. Restart Murmur to finish restoring it."); };
  const checkUpdates = async () => { try { const status = await bridge.checkForUpdates(); setSetup(status); setSetupReady(true); setNotice(status.update.state === "error" ? { kind: "error", text: status.update.detail } : { kind: "success", text: status.update.state === "ready" ? `Update ${status.update.version ?? ""} is ready for restart.`.replace("  ", " ") : "Murmur is current." }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } finally { clearProgress(); } };
  const installModel = async () => { try { setSetup(await bridge.installOfflineModel()); setSetupReady(true); setNotice({ kind: "success", text: "Offline model installed." }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } finally { clearProgress(); } };
  const removeData = async () => { try { const preview = await bridge.previewDataRemoval(); const typed = window.prompt(`This permanently deletes ${preview.bytes.toLocaleString()} bytes from:\n\n${preview.paths.join("\n")}\n\nType DELETE to continue.`); if (typed !== "DELETE") return; await bridge.removeUserData("DELETE"); setNotice({ kind: "success", text: "Murmur user data deleted." }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  return <main className="content-page settings-page page-enter"><header className="page-heading"><div><span className="eyebrow">Preferences and setup</span><h1>Settings</h1><p>Credentials stay in Windows Credential Manager. Murmur sends no telemetry.</p></div><Button className="primary" disabled={!prefsReady} icon={saved ? "check" : undefined} onClick={save}>{saved ? "Saved" : prefsReady ? "Save changes" : "Loading preferences"}</Button></header>
    {!bridge.isNative && <div className="inline-notice attention">Sample settings · Browser preview. Hardware and provider checks only run in the Windows app.</div>}{progress && <div className="setup-progress" role="status"><span>{progress.message}</span><progress max={100} value={progress.percent}/><strong>{progress.percent}%</strong></div>}
    {prefsError && <div className="inline-notice attention" role="alert"><span>Preferences could not load. {prefsError}</span><Button onClick={() => void loadPreferences()}>Retry preferences</Button></div>}
    {setupError && <div className="inline-notice attention" role="alert"><span>Setup status could not load. {setupError}</span><Button onClick={() => void loadSetup()}>Retry setup</Button></div>}
    {devicesError && <div className="inline-notice attention" role="alert"><span>Microphones could not load. {devicesError}</span><Button onClick={() => void loadDevices()}>Retry microphones</Button></div>}
    <fieldset className="settings-fieldset" disabled={!prefsReady}><section className="settings-group"><h2>Control</h2><SettingRow title="Hold-to-talk shortcut" description="Hold to record and release to transcribe."><input aria-label="Hold-to-talk shortcut" className="shortcut-input" value={prefs.holdShortcut} onChange={(e) => set("holdShortcut", e.target.value)}/></SettingRow><SettingRow title="Toggle shortcut" description="Press once to start, then again to stop."><input aria-label="Toggle shortcut" className="shortcut-input" value={prefs.toggleShortcut} onChange={(e) => set("toggleShortcut", e.target.value)}/></SettingRow><SettingRow title="Microphone" description="Use the Windows default unless you deliberately override it."><select aria-label="Microphone" value={prefs.microphoneId ?? ""} onChange={(e) => set("microphoneId", e.target.value || null)}><option value="">Windows default</option>{devices.map((device) => <option key={device.id} value={device.id}>{device.label}{device.isDefault ? " · Default" : ""}</option>)}</select></SettingRow><SettingRow title="Dictation cleanup" description={prefs.cleanupLevel === "medium" ? "Medium keeps only your self-corrections, drops fillers, and fixes obvious misheard words." : "Light fixes punctuation and grammar and keeps your words, including self-corrections."}><select aria-label="Dictation cleanup" value={prefs.cleanupLevel} onChange={(e) => set("cleanupLevel", e.target.value as CleanupLevel)}><option value="light">Light</option><option value="medium">Medium</option></select></SettingRow></section>
    <section className="settings-group"><h2>General</h2><SettingRow title="Launch with Windows" description="Keep Murmur ready in the tray."><Toggle label="Launch with Windows" checked={prefs.launchAtStartup} onChange={(value) => set("launchAtStartup", value)}/></SettingRow><SettingRow title="Meeting suggestions" description="Offer to start when a supported call begins and stop when it ends."><Toggle label="Meeting suggestions" checked={prefs.meetingSuggestions} onChange={(value) => set("meetingSuggestions", value)}/></SettingRow></section>
    <section className="settings-group"><h2>Privacy and context</h2><SettingRow title="Capture focused context" description="Use selected and nearby text for correction, then discard it."><Toggle label="Capture focused context" checked={prefs.contextCapture} onChange={(value) => set("contextCapture", value)}/></SettingRow><button className="setting-link" onClick={() => setExcluded(!excluded)}><span><strong>Excluded applications</strong><small>Password fields, private windows, and security dialogs are always excluded.</small></span><span>{prefs.excludedApplications.length} apps <Icon name="chevron" size={15}/></span></button>{excluded && <div className="exclusion-editor">{prefs.excludedApplications.map((app) => <span key={app}>{app}<button aria-label={`Remove ${app}`} onClick={() => set("excludedApplications", prefs.excludedApplications.filter((item) => item !== app))}><Icon name="x" size={12}/></button></span>)}<Button onClick={() => void act(async () => { const app = await bridge.chooseContextApplication(); if (app && !prefs.excludedApplications.includes(app)) set("excludedApplications", [...prefs.excludedApplications, app]); })}>Add running app</Button></div>}</section>
    <section className="settings-group"><h2>Storage</h2><SettingRow title="Dictation history" description="Raw transcripts and results expire automatically."><select aria-label="Dictation history" value={prefs.dictationRetentionDays} onChange={(e) => set("dictationRetentionDays", Number(e.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></SettingRow><SettingRow title="Meeting history" description="Pinned meetings do not expire."><select aria-label="Meeting history" value={prefs.meetingRetentionDays} onChange={(e) => set("meetingRetentionDays", Number(e.target.value))}><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option></select></SettingRow><SettingRow title="Backup" description="Plain ZIP includes local data and audio, but never credentials."><span className="setting-actions"><Button onClick={backup}>Create backup</Button><Button onClick={restore}>Restore</Button></span></SettingRow></section>
    </fieldset>{setupReady ? <><section className="settings-group"><h2>Speech providers</h2>{setup.providers.map((provider) => <SettingRow key={provider.id} title={provider.label} description={provider.detail}><span className="setting-actions"><StateTag state={provider.state}/><Button onClick={() => provider.configured ? validate(provider.id) : setCredential(provider)}>{provider.configured ? "Test" : "Set up"}</Button></span></SettingRow>)}</section><section className="settings-group"><h2>Device checks</h2>{setup.checks.map((check) => <SettingRow key={check.id} title={check.label} description={check.detail}><span className="setting-actions"><StateTag state={check.state}/>{check.id === "offline" && check.state !== "ready" ? <Button onClick={() => void installModel()}>Install model</Button> : <Button onClick={() => runCheck(check.id)}>Run check</Button>}</span></SettingRow>)}</section></> : <section className="settings-group"><h2>Setup status</h2><div className="setting-row"><span><strong>Setup status unavailable</strong><small>Retry after resolving the error shown above.</small></span></div></section>}
    <section className="settings-group"><h2>Maintenance</h2><SettingRow title="Diagnostics" description="Export redacted logs and setup checks."><Button onClick={() => void fileAction(() => bridge.exportDiagnostics(), "Diagnostics exported.")}>Export diagnostics</Button></SettingRow>{setupReady && <SettingRow title="Automatic updates" description={setup.update.detail}><span className="setting-actions"><StateTag state={setup.update.state}/><Button onClick={() => void checkUpdates()}>Check now</Button></span></SettingRow>}</section><section className="settings-group danger-zone"><h2>Destructive actions</h2><SettingRow title="Delete all Murmur data" description="Shows every target path before permanent deletion. Ordinary uninstall keeps this data."><Button className="danger" onClick={() => void removeData()}>Review and delete</Button></SettingRow></section>{credential && <CredentialDialog provider={credential} onClose={() => setCredential(null)} onSave={async (secret) => { try { await bridge.setProviderCredential(credential.id, secret); setSetup(await bridge.validateProvider(credential.id)); setCredential(null); setNotice({ kind: "success", text: `${credential.label} connected and tested.` }); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } }}/>}
  </main>;
}

function Onboarding({ onDone }: { onDone: () => void }) {
  const [step, setStep] = useState(0); const [consent, setConsent] = useState(false);
  const steps = [{ eyebrow: "Welcome to Murmur", title: "Hold Ctrl + Win and speak", body: "Release to transcribe, correct, and insert into the app in focus." }, { eyebrow: "Recording responsibility", title: "You decide when meetings start", body: "Murmur can suggest a meeting. It never records automatically. Get consent and follow local recording laws." }, { eyebrow: "Setup", title: "Check the paths that matter", body: "Murmur will test your microphone, insertion, provider keys, and offline model in Settings." }]; const current = steps[step];
  return <div className="modal-backdrop"><section className="onboarding" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div className="onboarding-art"><div className="voice-rings"><i/><i/><i/><span><Icon name="mic" size={28}/></span></div><p>English + Tiếng Việt</p></div><div className="onboarding-copy"><span className="eyebrow">{current.eyebrow}</span><h1 id="onboarding-title">{current.title}</h1><p>{current.body}</p>{step === 0 && <div className="shortcut-demo"><kbd>Ctrl</kbd><span>+</span><kbd>Win</kbd><span className="hold-line">Hold to talk</span></div>}{step === 1 && <label className="consent-check"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)}/> I understand that I must get consent before recording.</label>}<div className="onboarding-footer"><div className="step-dots" aria-label={`Step ${step + 1} of 3`}>{steps.map((_, index) => <i key={index} className={step === index ? "active" : ""}/>)}</div><Button className="primary" disabled={step === 1 && !consent} onClick={() => step === 2 ? onDone() : setStep(step + 1)}>{step === 2 ? "Open Murmur" : "Continue"}</Button></div></div></section></div>;
}

export function App() {
  const overlayOnly = new URLSearchParams(window.location.search).get("overlay") === "1";
  const [view, setView] = useState<View>("library"); const [meetingId, setMeetingId] = useState<string | null>(bridge.isNative ? null : sampleMeeting.id); const [dictation, setDictation] = useState<DictationEvent | null>(null); const [meetingState, setMeetingState] = useState<MeetingEvent | null>(null); const [prompt, setPrompt] = useState<MeetingPromptEvent | null>(null); const [progress, setProgress] = useState<SetupProgressEvent | null>(null); const [notice, setNotice] = useState<Notice>(null); const [showOnboarding, setShowOnboarding] = useState(() => localStorage.getItem("murmur.onboarding.complete") !== "1");
  useEffect(() => { document.documentElement.classList.toggle("overlay-document", overlayOnly); return () => document.documentElement.classList.remove("overlay-document"); }, [overlayOnly]);
  useEffect(() => { if (!bridge.isNative) return; const offs: Array<() => void> = []; void bridge.listen("murmur://dictation-state", setDictation).then((off) => offs.push(off)); void bridge.listen("murmur://meeting-state", setMeetingState).then((off) => offs.push(off)); void bridge.listen("murmur://meeting-prompt", setPrompt).then((off) => offs.push(off)); void bridge.listen("murmur://connectivity", ({ online }) => setNotice(online ? { kind: "success", text: "Back online. Pending meeting work will resume." } : { kind: "attention", text: "Offline. Dictation will rotate to local speech. Meeting enhancement is queued." })).then((off) => offs.push(off)); void bridge.listen("murmur://audio-device", ({ state, message }) => setNotice({ kind: state === "lost" ? "attention" : "success", text: message })).then((off) => offs.push(off)); void bridge.listen("murmur://setup-progress", setProgress).then((off) => offs.push(off)); return () => offs.forEach((off) => off()); }, []);
  useEffect(() => { if (overlayOnly || !dictation || !["inserted", "clipboard", "raw", "failed", "cancelled"].includes(dictation.state)) return; const timer = window.setTimeout(() => setDictation(null), 2200); return () => window.clearTimeout(timer); }, [dictation, overlayOnly]);
  useEffect(() => { if (!progress || progress.percent < 100) return; const timer = window.setTimeout(() => setProgress(null), 1600); return () => window.clearTimeout(timer); }, [progress]);
  const openMeeting = (id: string) => { setMeetingId(id); setView("meeting"); };
  const navigate = (next: View) => { if (next !== "meeting" || meetingId || !bridge.isNative) { setView(next); return; } void bridge.listSessions().then((sessions) => { const first = sessions.find((session) => session.kind === "meeting"); if (first) openMeeting(first.id); else setView("meeting"); }).catch((error) => { setNotice({ kind: "error", text: `Meetings could not be loaded. ${errorMessage(error)}` }); setView("meeting"); }); };
  const finishOnboarding = () => { localStorage.setItem("murmur.onboarding.complete", "1"); setShowOnboarding(false); setView("settings"); };
  const promptAction = async () => { if (!prompt) return; try { if (prompt.kind === "start") await bridge.startMeeting("online"); else await bridge.stopMeeting(); setPrompt(null); } catch (error) { setNotice({ kind: "error", text: errorMessage(error) }); } };
  const dismissPrompt = (disableForApp: boolean) => { if (!prompt) return; void bridge.dismissMeetingPrompt(prompt.appName, disableForApp).then(() => setPrompt(null)).catch((error) => setNotice({ kind: "error", text: errorMessage(error) })); };
  if (overlayOnly) return <div className="overlay-shell"><DictationAnnouncer event={dictation}/>{notice?.kind === "error" ? <NoticeBar notice={notice} onDismiss={() => setNotice(null)}/> : <DictationOverlay event={dictation} onCancel={() => void bridge.cancelDictation().catch((error) => setNotice({ kind: "error", text: `Cancel failed. ${errorMessage(error)}` }))} onStop={() => void bridge.stopDictation().catch((error) => setNotice({ kind: "error", text: `Stop failed. ${errorMessage(error)}` }))}/>}</div>;
  return <div className="app-shell"><AppHeader view={view} onNavigate={navigate}/>{notice && <NoticeBar notice={notice} onDismiss={() => setNotice(null)}/>} {view === "library" && <Library onOpenMeeting={openMeeting} onNavigateSettings={() => setView("settings")} dictation={dictation} meetingState={meetingState} setNotice={setNotice}/>} {view === "meeting" && <Meeting id={meetingId} onBack={() => setView("library")} setNotice={setNotice}/>} {view === "vocabulary" && <Vocabulary setNotice={setNotice}/>} {view === "settings" && <Settings setNotice={setNotice} progress={progress} clearProgress={() => setProgress(null)}/>} {prompt && <MeetingPrompt prompt={prompt} onDismiss={() => dismissPrompt(false)} onDisable={() => dismissPrompt(true)} onAction={() => void promptAction()}/>} {showOnboarding && <Onboarding onDone={finishOnboarding}/>}</div>;
}
